services:
  - type: web
    name: citimart-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    disk:
      name: uploads
      mountPath: /app/static/uploads
      sizeGB: 1
